os: osx
language: node_js
node_js:
  - "10.15.3"
before_install:
  - brew install mongodb-community@4.0
  - brew services start mongodb-community@4.0
  - npm i
jobs:
  include:
    - stage: test
      script:
        - npm run test:travis
