language: node_js
node_js:
  - "10.15.3"
before_install:
  - npm i
cache:
  - directories:
      - node_modules
services:
  - mongodb
jobs:
  include:
    - stage: test
      script:
        - npm run test:travis
