language: node_js
node_js:
  - "node"
before_install:
  - npm i
cache:
  - directories:
    - node_modules
services:
  - mongodb
jobs:
  include:
    - stage: test
      script:
        - npm test:travis
